# Generated by Django 4.2.4 on 2023-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0002_enrollment_membershipplan_trainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Selectdate", models.DateTimeField(auto_now_add=True)),
                ("phonenumber", models.CharField(max_length=15)),
                ("Login", models.CharField(max_length=200)),
                ("Logout", models.CharField(max_length=200)),
                ("SelectWorkout", models.CharField(max_length=200)),
                ("TrainedBy", models.CharField(max_length=200)),
            ],
        ),
    ]
