# Generated by Django 4.2.4 on 2023-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0003_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="gallery")),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
